apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: team036
spec:
  type: NodePort
  selector:
    app: backend
  ports:
    - port: 30090
      targetPort: 30090
      nodePort: 30090 