apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: team036
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: team036-backend:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 30090
          env:
            - name: GIN_MODE
              value: "release"
            - name: DB_HOST
              value: "database-service"
            - name: DB_PORT
              value: "5432"
            - name: DB_USER
              value: "postgres"
            - name: DB_PASSWORD
              value: "postgres"
            - name: DB_NAME
              value: "loans"
          volumeMounts:
            - name: config-volume
              mountPath: /app/configs/config.yaml
              subPath: config.yaml
      volumes:
        - name: config-volume
          configMap:
            name: backend-config 