apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: team036
data:
  config.yaml: |
    app:
      name: "My Gin App"
      port: 30090
    database:
      host: "database-service"
      port: 5432
      user: "postgres"
      password: "postgres"
      dbname: "loans" 