apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: team036
spec:
  type: NodePort
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 30080
      targetPort: 30080
      nodePort: 30080
