apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: team036

resources:
  - namespace.yaml
  - backend-deployment.yaml
  - backend-service.yaml
  - postgres-deployment.yaml
  - postgres-service.yaml
  - backend-config.yaml
  - postgres-pvc.yaml
  - create-loan-table-sql-configmap.yaml
  - frontend-deployment.yaml
  - frontend-service.yaml 