apiVersion: v1
kind: Service
metadata:
  name: database-service
  namespace: team036
spec:
  type: NodePort
  selector:
    app: postgres
  ports:
    - port: 5432
      targetPort: 5432
      nodePort: 30050 
      protocol: TCP
